name: Rani Dilipkumar Shiva Shankar
description: If I have seen further than others, it is by standing upon the shoulders of giants - Isaac Newton
meta_description: "Hello there, I am shankar studying Electrical Engineering in National University of Singapore"
meta_tags: "shankar, sp, singapore polytechnic, electrical, electrical engineering, nus, national university of singapore, eee"

aboutPage: true

markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM

plugins:
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-redirect-from

paginate: 10
baseurl:
domain_name: "https://shankar-shiv.github.io"

#social-icons
twitter:
instagram:
linkedin:
github:
email:

# Details for the RSS feed generator
url: "https://shankar-shiv.github.io"
author: "Rani Dilipkumar Shiva Shankar"
authorTwitter:

permalink: /:year/:title/

defaults:
    - scope:
          path: "" # empty string for all files
          type: pages
      values:
          layout: default
    - scope:
          path: "" # empty string for all files
          type: posts
      values:
          layout: post
    - scope:
          path: ""
          type: drafts
      values:
          layout: post
