name: Shiva Shankar
description: nanos gigantum humeris insidentes - Dwarfs standing on the shoulders of giants
meta_description: "Hello, my name is Shankar, and I am a undergraduate student pursuing Electrical Engineering with an IoT Specialization at the National University of Singapore ."
meta_tags: "shankar, sp, singapore polytechnic, computer science, electrical engineering, nus, national university of singapore, eee"

aboutPage: true

markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM

plugins:
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-seo-tag

paginate: 10
baseurl:
domain_name: "https://shankar-shiv.github.io"

#social-icons
twitter:
instagram:
linkedin:
github:
email:

share-links-active:
    twitter: true
    facebook: true
    linkedin: true

# Details for the RSS feed generator
url: "https://shankar-shiv.github.io"
author: "Shiva Shankar"
authorTwitter:

permalink: /:year/:title/

defaults:
    - scope:
          path: "" # empty string for all files
          type: pages
      values:
          layout: default
    - scope:
          path: "" # empty string for all files
          type: posts
      values:
          layout: post
    - scope:
          path: ""
          type: drafts
      values:
          layout: post
